FROM continuumio/miniconda3:latest
MAINTAINER Ryan Rodriguez <ryarodri@ucsc.edu>

ADD ./environment.yml environment.yml

# update conda and setup environment
RUN conda update conda -y \
    && conda install pyyaml \
    && conda env create -f environment.yml

ENV PATH /opt/conda/envs/panopticon/bin:$PATH

# Zmq Sub Server
EXPOSE 5555 5558

ADD ./gritty_soap /panopticon/gritty_soap
ADD ./panopticon /panopticon/panopticon

ADD OpcXMLDaServer.asmx /panopticon/OpcXMLDaServer.asmx
ADD setup.py panopticon/setup.py
ADD ./panopticon/execute.py /panopticon/execute.py
RUN cd panopticon && python setup.py install
WORKDIR /panopticon
