name: panopticon
channels: !!python/tuple
- defaults
dependencies:
- lxml=3.6.4=py34_0
- pip=8.1.2=py34_0
- python=3.4.5=0
- pytz=2016.7=py34_0
- pyzmq=16.0.0=py34_0
- setuptools=27.2.0=py34_0
- wheel=0.29.0=py34_0
- pip:
  - appdirs==1.4.0
  - attrs==16.2.0
  - cached-property==1.3.0
  - click==6.6
  - defusedxml==0.4.1
  - flask==0.11.1
  - flask-login==0.4.0
  - flask-mongoengine==0.8
  - flask-wtf==0.13.1
  - isodate==0.5.4
  - itsdangerous==0.24
  - jinja2==2.8
  - markupsafe==0.23
  - msgpack-python==0.4.8
  - pymongo==3.3.1
  - requests==2.11.1
  - six==1.10.0
  - structlog==16.1.0
  - werkzeug==0.11.11
  - wtforms==2.1




