# -*- mode: ruby -*-
# vi: set ft=ruby :

# Conda Install Script
$conda_installation = <<SCRIPT
sudo apt-get update;
sudo apt-get install bzip2;
which conda
if [[ ${?} -ne 0 ]]; then
    wget -nc http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /home/vagrant/miniconda.sh || exit 1;
    bash miniconda.sh -b -p /home/vagrant/miniconda  || exit 1;
    echo 'PATH="/home/vagrant/miniconda/bin:$PATH"'>> /etc/profile
fi
source /etc/profile;
conda info || exit 1;
ls | grep -i miniconda.*\.sh | xargs -d"\n" rm || exit 1;
SCRIPT

# conda create --name opc python=3.5

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # We should think about switching to a lighter-weight box when we get the chance
  config.vm.define "vagrant-ubuntu1404x64"
  config.vm.box = "puphpet/ubuntu1404-x64"

    #config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    #config.vm.network :forwarded_port, guest: 22, host: 2223, auto_correct: true

    #config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2223, auto_correct: true
    #config.ssh.host = "localhost"
    #config.ssh.port = 2223

    config.vm.provider :virtualbox do |v, override|
        v.gui = true
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--vram", "256"]
        v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
        v.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
        v.customize ["modifyvm", :id, "--accelerate3d", "on"]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: $conda_installation

end


